version: '3.3'
volumes:
  data:
services:
  database_mysql:
    image: mysql:5.6
    ports:
      - "3306:${MYSQL_PORT}"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - database_mysql
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1